version: 2
jobs:
  lint:
    docker:
      - image: circleci/golang:1.12.1
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/vmware/hamlet/
    steps:
      - checkout
      - run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.19.1
      - run: golangci-lint run
  build:
    docker:
      - image: circleci/golang:1.12.1
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/vmware/hamlet/
    steps:
      - checkout
      # TODO: Add a run step for compiling proto files.
      - run: go build -v ./...
  test:
    docker:
      - image: circleci/golang:1.12.1
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/vmware/hamlet/
    steps:
      - checkout
      - run: go test -v ./...
workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - build
      - test
