version: 2
jobs:
  lint:
    docker:
      - image: circleci/golang:1.12.1
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/vmware/hamlet/
    steps:
      - checkout
      - run:
          command: |
            curl -O -L https://github.com/nilslice/protolock/releases/download/v0.14.1/protolock.20190917T024843Z.linux-amd64.tgz
            tar -zxvf protolock.20190917T024843Z.linux-amd64.tgz
            sudo mv protolock /usr/local/bin/
            rm -rf protolock.20190917T024843Z.linux-amd64.tgz
      - run: protolock status
      - run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.19.1
      - run: golangci-lint run
  build:
    docker:
      - image: circleci/golang:1.12.1
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/vmware/hamlet/
    steps:
      - checkout
      # TODO: Add a run step for compiling proto files.
      - run: go build -v ./...
  test:
    docker:
      - image: circleci/golang:1.12.1
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/vmware/hamlet/
    steps:
      - checkout
      - run: go test -v ./...
workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - build
      - test
