// Code generated by protoc-gen-go. DO NOT EDIT.
// source: federated_service.proto

package v1alpha2

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// FederatedService represents a federated service which can be discovered by
// a federated service mesh consumer.
type FederatedService struct {
	// REQUIRED. The unique name that identifies the service within a federated
	// service mesh owner.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The description of the federated service.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Informative values for filtering purposes.
	Tags []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	// Informative KV pairs for filtering purposes.
	Labels map[string]string `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// REQUIRED. The FQDN (Fully Qualified Domain Name) uniquely identifies the
	// federated service. The FQDN is used by consumer platforms as a DNS name to
	// access the imported FederatedService. The consumer platform DNS can be
	// programmed to reference the Ingress of the imported FederatedService.
	Fqdn string `protobuf:"bytes,5,opt,name=fqdn,proto3" json:"fqdn,omitempty"`
	// REQUIRED. The service mesh ingress endpoints that provide access to the
	// federated service.
	Endpoints []*FederatedService_Endpoint `protobuf:"bytes,9,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	// REQUIRED. A list of SANs (Subject Alternative Names) to enable end-to-end
	// security for the federated service.
	Sans []string `protobuf:"bytes,10,rep,name=sans,proto3" json:"sans,omitempty"`
	// REQUIRED. The service instances corresponding to the federated service.
	Instances            []*FederatedService_Instance `protobuf:"bytes,11,rep,name=instances,proto3" json:"instances,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *FederatedService) Reset()         { *m = FederatedService{} }
func (m *FederatedService) String() string { return proto.CompactTextString(m) }
func (*FederatedService) ProtoMessage()    {}
func (*FederatedService) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ca57f12e11e216c, []int{0}
}

func (m *FederatedService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FederatedService.Unmarshal(m, b)
}
func (m *FederatedService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FederatedService.Marshal(b, m, deterministic)
}
func (m *FederatedService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FederatedService.Merge(m, src)
}
func (m *FederatedService) XXX_Size() int {
	return xxx_messageInfo_FederatedService.Size(m)
}
func (m *FederatedService) XXX_DiscardUnknown() {
	xxx_messageInfo_FederatedService.DiscardUnknown(m)
}

var xxx_messageInfo_FederatedService proto.InternalMessageInfo

func (m *FederatedService) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FederatedService) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *FederatedService) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *FederatedService) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *FederatedService) GetFqdn() string {
	if m != nil {
		return m.Fqdn
	}
	return ""
}

func (m *FederatedService) GetEndpoints() []*FederatedService_Endpoint {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

func (m *FederatedService) GetSans() []string {
	if m != nil {
		return m.Sans
	}
	return nil
}

func (m *FederatedService) GetInstances() []*FederatedService_Instance {
	if m != nil {
		return m.Instances
	}
	return nil
}

// Endpoint represents a service mesh ingress endpoint that provides access to
// a federated service over mTLS (mutual TLS).
type FederatedService_Endpoint struct {
	// REQUIRED. The service mesh ingress endpoint address (i.e. IP, CIDR, or a
	// domain name).
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// REQUIRED. The port exposed by the service mesh ingress endpoint.
	Port uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	// REQUIRED. The endpoint labels decouple IP from routing information. The
	// endpoint_selector field in Instance matches with at least one endpoint
	// label here.
	Labels               []string `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FederatedService_Endpoint) Reset()         { *m = FederatedService_Endpoint{} }
func (m *FederatedService_Endpoint) String() string { return proto.CompactTextString(m) }
func (*FederatedService_Endpoint) ProtoMessage()    {}
func (*FederatedService_Endpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ca57f12e11e216c, []int{0, 1}
}

func (m *FederatedService_Endpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FederatedService_Endpoint.Unmarshal(m, b)
}
func (m *FederatedService_Endpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FederatedService_Endpoint.Marshal(b, m, deterministic)
}
func (m *FederatedService_Endpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FederatedService_Endpoint.Merge(m, src)
}
func (m *FederatedService_Endpoint) XXX_Size() int {
	return xxx_messageInfo_FederatedService_Endpoint.Size(m)
}
func (m *FederatedService_Endpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_FederatedService_Endpoint.DiscardUnknown(m)
}

var xxx_messageInfo_FederatedService_Endpoint proto.InternalMessageInfo

func (m *FederatedService_Endpoint) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *FederatedService_Endpoint) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *FederatedService_Endpoint) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

// Instance represents an instance of the federated service.
type FederatedService_Instance struct {
	// REQUIRED. The unique identifier for the federated service instance within
	// the group of instances for a FederatedService.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// REQUIRED. The protocol corresponding to the federated service instance.
	//
	// E.g. In the case where protocol is TLS, the connection will be routed
	// based on the SNI header to the destination.
	Protocol string `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// Additional metadata for the purpose of establishing connectivity.
	//
	// E.g. In the case where protocol is TLS, the connection will be routed
	// based on the SNI header to the destination. The SNI header can be made
	// available in the metadata using a key named 'sni'.
	Metadata map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// REQUIRED. A list of endpoint labels to match over Endpoint instances in a
	// FederatedService. At least one matching label must be provided.
	EndpointSelector     []string `protobuf:"bytes,4,rep,name=endpoint_selector,json=endpointSelector,proto3" json:"endpoint_selector,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FederatedService_Instance) Reset()         { *m = FederatedService_Instance{} }
func (m *FederatedService_Instance) String() string { return proto.CompactTextString(m) }
func (*FederatedService_Instance) ProtoMessage()    {}
func (*FederatedService_Instance) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ca57f12e11e216c, []int{0, 2}
}

func (m *FederatedService_Instance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FederatedService_Instance.Unmarshal(m, b)
}
func (m *FederatedService_Instance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FederatedService_Instance.Marshal(b, m, deterministic)
}
func (m *FederatedService_Instance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FederatedService_Instance.Merge(m, src)
}
func (m *FederatedService_Instance) XXX_Size() int {
	return xxx_messageInfo_FederatedService_Instance.Size(m)
}
func (m *FederatedService_Instance) XXX_DiscardUnknown() {
	xxx_messageInfo_FederatedService_Instance.DiscardUnknown(m)
}

var xxx_messageInfo_FederatedService_Instance proto.InternalMessageInfo

func (m *FederatedService_Instance) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *FederatedService_Instance) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *FederatedService_Instance) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *FederatedService_Instance) GetEndpointSelector() []string {
	if m != nil {
		return m.EndpointSelector
	}
	return nil
}

func init() {
	proto.RegisterType((*FederatedService)(nil), "federation.types.v1alpha2.FederatedService")
	proto.RegisterMapType((map[string]string)(nil), "federation.types.v1alpha2.FederatedService.LabelsEntry")
	proto.RegisterType((*FederatedService_Endpoint)(nil), "federation.types.v1alpha2.FederatedService.Endpoint")
	proto.RegisterType((*FederatedService_Instance)(nil), "federation.types.v1alpha2.FederatedService.Instance")
	proto.RegisterMapType((map[string]string)(nil), "federation.types.v1alpha2.FederatedService.Instance.MetadataEntry")
}

func init() { proto.RegisterFile("federated_service.proto", fileDescriptor_0ca57f12e11e216c) }

var fileDescriptor_0ca57f12e11e216c = []byte{
	// 419 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x4f, 0x8b, 0xd4, 0x30,
	0x14, 0x67, 0xda, 0x6e, 0x27, 0x7d, 0x65, 0x97, 0x1a, 0x44, 0x63, 0x4f, 0xc5, 0xd3, 0x82, 0x50,
	0x71, 0x14, 0xfc, 0x77, 0x5b, 0x58, 0xc1, 0x41, 0x51, 0xb2, 0x37, 0x0f, 0x2e, 0xd9, 0xe6, 0xad,
	0x16, 0xbb, 0x69, 0x4d, 0xe2, 0xc0, 0xdc, 0xfc, 0x4e, 0x7e, 0x41, 0x49, 0x9a, 0xcc, 0x8e, 0x82,
	0x87, 0xf1, 0xf6, 0x5e, 0x1e, 0xbf, 0x7f, 0xef, 0x05, 0xee, 0x5f, 0xa3, 0x44, 0x2d, 0x2c, 0xca,
	0x4b, 0x83, 0x7a, 0xd3, 0x77, 0xd8, 0x4e, 0x7a, 0xb4, 0x23, 0x7d, 0x10, 0x06, 0xfd, 0xa8, 0x5a,
	0xbb, 0x9d, 0xd0, 0xb4, 0x9b, 0x27, 0x62, 0x98, 0xbe, 0x8a, 0xd5, 0xc3, 0x5f, 0x39, 0x54, 0x6f,
	0x22, 0xec, 0x62, 0x46, 0x51, 0x0a, 0x99, 0x12, 0x37, 0xc8, 0x16, 0xcd, 0xe2, 0xb4, 0xe0, 0xbe,
	0xa6, 0x0d, 0x94, 0x12, 0x4d, 0xa7, 0xfb, 0xc9, 0xd1, 0xb0, 0xc4, 0x8f, 0xf6, 0x9f, 0x1c, 0xca,
	0x8a, 0x2f, 0x86, 0xa5, 0x4d, 0xea, 0x50, 0xae, 0xa6, 0x1f, 0x20, 0x1f, 0xc4, 0x15, 0x0e, 0x86,
	0x65, 0x4d, 0x7a, 0x5a, 0xae, 0x9e, 0xb7, 0xff, 0xb4, 0xd2, 0xfe, 0x6d, 0xa3, 0x7d, 0xe7, 0x91,
	0xe7, 0xca, 0xea, 0x2d, 0x0f, 0x34, 0x4e, 0xe4, 0xfa, 0xbb, 0x54, 0xec, 0x68, 0xb6, 0xe6, 0x6a,
	0xca, 0xa1, 0x40, 0x25, 0xa7, 0xb1, 0x57, 0xd6, 0xb0, 0xc2, 0xeb, 0x3c, 0x3b, 0x44, 0xe7, 0x3c,
	0x80, 0xf9, 0x2d, 0x8d, 0xd3, 0x31, 0x42, 0x19, 0x06, 0x73, 0x18, 0x57, 0x3b, 0x9d, 0x5e, 0x19,
	0x2b, 0x54, 0x87, 0x86, 0x95, 0x87, 0xeb, 0xbc, 0x0d, 0x60, 0x7e, 0x4b, 0x53, 0xbf, 0x84, 0x72,
	0x2f, 0x26, 0xad, 0x20, 0xfd, 0x86, 0xdb, 0xb0, 0x78, 0x57, 0xd2, 0xbb, 0x70, 0xb4, 0x11, 0xc3,
	0x0f, 0x0c, 0x1b, 0x9f, 0x9b, 0x57, 0xc9, 0x8b, 0x45, 0xfd, 0x11, 0x48, 0x74, 0x4e, 0x19, 0x2c,
	0x85, 0x94, 0x1a, 0x8d, 0x09, 0xd8, 0xd8, 0xba, 0x20, 0xd3, 0xa8, 0xad, 0x87, 0x1f, 0x73, 0x5f,
	0xd3, 0x7b, 0xbb, 0xab, 0xcc, 0xb7, 0x0a, 0x5d, 0xfd, 0x33, 0x01, 0x12, 0x4d, 0xd2, 0x13, 0x48,
	0x7a, 0x19, 0xd8, 0x92, 0x5e, 0xd2, 0x1a, 0x88, 0xff, 0x4d, 0xdd, 0x38, 0x04, 0x2f, 0xbb, 0x9e,
	0x7e, 0x06, 0x72, 0x83, 0x56, 0x48, 0x61, 0x85, 0xa7, 0x2c, 0x57, 0x67, 0xff, 0xb3, 0x98, 0xf6,
	0x7d, 0x20, 0x99, 0x6f, 0xbe, 0xe3, 0xa4, 0x8f, 0xe0, 0x4e, 0x3c, 0xcd, 0xa5, 0xc1, 0x01, 0x3b,
	0x3b, 0x6a, 0xff, 0xa3, 0x0a, 0x5e, 0xc5, 0xc1, 0x45, 0x78, 0xaf, 0x5f, 0xc3, 0xf1, 0x1f, 0x3c,
	0x87, 0x2c, 0x75, 0x9d, 0x91, 0xbc, 0x5a, 0xae, 0x33, 0xb2, 0xac, 0xc8, 0x3a, 0x23, 0xa4, 0xf2,
	0xd9, 0x79, 0x6a, 0x84, 0xe2, 0x45, 0x8c, 0x6b, 0xce, 0xaa, 0x4f, 0x27, 0x3e, 0xd3, 0xe3, 0x98,
	0xe9, 0x2a, 0xf7, 0xc3, 0xa7, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x6d, 0x91, 0xdf, 0x15, 0x84,
	0x03, 0x00, 0x00,
}
